### ISSUE TITLE
Snowflake Minimal VS/MVP

### ISSUE THREAD

**Issue by pj-spoelders** [exasol/snowflake-virtual-schema#1]
Get a basic VS working with basic SELECT on Snowflake tables.

**Comment by redcatbear** [comment]
Metadata pulling done.

Underscore behaves weirdly in Snowflake. Acts as a wildcard.

**Comment by pj-spoelders** [comment]
Fixed issue encountered by switching test accounts ("No database context")
Got 15/60 current integration tests working. 
Working on enabling the other test schemas and then go over the remaining failing tests case by case.

**Comment by pj-spoelders** [comment]
Had some issues with Git merge yesterday ~2h
Had some issues with PK and version docs yesterday ~2h
CI is now also working in PRs. Most integration tests work
Still have issues with
- timestamp with timezone
- char (empty spacing/padding missing)
- decimal/number with higher precision
- investigating other more exotic snowflake datatypes right now

Will see what I can fix and document/report on outstanding issues to TB
Also started work on documentation

**Comment by redcatbear** [comment]
Documentation pending.
Need to consult with TB about column type mapping strategy.

**Comment by redcatbear** [comment]
Documentation done.
Will execute instructions in documentation to verify them.
